# Configuration file for Travis CI (https://travis-ci.org)
#
# It used as a status check for all PRs and
# to generate the build-status-icon in the main README.md-file.

dist: xenial
language: python
python: 3.7

before_install:
  - sudo apt-get install -y wkhtmltopdf
  - sudo apt-get install -y xvfb
  - sudo echo -e '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" wkhtmltopdf -q $*' > wkhtmltopdf2.sh
  - sudo chmod a+x wkhtmltopdf2.sh
  - sudo ln -s wkhtmltopdf2.sh wkhtmltopdf_exec
install:
  - pip install grip

script:
  - grip "3MF Core Specification.md" --export "Spec.html"
  - ./fixHtmlBugs.sh Spec.html SpecFixed.html
  - ./wkhtmltopdf_exec --enable-toc-back-links --enable-internal-links SpecFixed.html Spec.pdf
deploy:
  provider: releases 
  api_key: '$GITHUB_API_KEY'
  file: Spec.pdf
  skip_cleanup: true
  draft: true
